purpose: 'default config'

# metrics
metrics:
    accuracy: true
    iou_micro: true
    iou_macro: true
    iou_weighted: true
    crossentropy: true
    crossentropy_weighted: true

# model options
model:
    input_channels: 1
    output_channels: 4
    hidden_channels: 8
    learning_rate: 0.001
    dropout: 0.25                          # rate of the dropout
    loss: 'iou macro loss'                 # loss function
    optimizer: 'adam'                      # optimizer
    model_summary: false                   # print the model.summary
    deep_unet: 4

# data options
data:
    data_path: 'data'                      # path to the data
    train_split: 0.1
    val_split: 0.1
    shuffle: true
    number_of_channels: 1
    number_classes: 4

# train options
train:
    batch_size: 1                          # training batch size
    virtual_batch_size: 10
    epochs: 2                              # number of epochs
    save_learning_curves: true             # save the learning curves
    logs_path: 'logs'                      # path to logs folder
    save_checkpoint: true                  # if you want save the model's weight: 'all', 'last' or false

# validation options
val:
    batch_size: 1                          # validation batch size

# test options
test:
    batch_size: 1                          # test batch size
    checkpoint: null


